//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", ConfigurationName="Service")]
public interface Service
{
    
    // CODEGEN: Контракт генерации сообщений с операцией GetStatus не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/GetStatus")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    GetStatusResponse1 GetStatus(GetStatusRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией Read не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/Read")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    ReadResponse1 Read(ReadRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией Write не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/Write")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    WriteResponse1 Write(WriteRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией Subscribe не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/Subscribe")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    SubscribeResponse1 Subscribe(SubscribeRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией SubscriptionPolledRefresh не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionPolledRefresh")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    SubscriptionPolledRefreshResponse1 SubscriptionPolledRefresh(SubscriptionPolledRefreshRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией SubscriptionCancel не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionCancel")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    SubscriptionCancelResponse1 SubscriptionCancel(SubscriptionCancelRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией Browse не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/Browse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    BrowseResponse1 Browse(BrowseRequest request);
    
    // CODEGEN: Контракт генерации сообщений с операцией GetProperties не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action="http://opcfoundation.org/webservices/XMLDA/1.0/GetProperties")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(float[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ulong[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ushort[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(bool[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.DateTime[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decimal[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sbyte[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(short[]))]
    GetPropertiesResponse1 GetProperties(GetPropertiesRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class GetStatus
{
    
    private string localeIDField;
    
    private string clientRequestHandleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocaleID
    {
        get
        {
            return this.localeIDField;
        }
        set
        {
            this.localeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class PropertyReplyList
{
    
    private ItemProperty[] propertiesField;
    
    private string itemPathField;
    
    private string itemNameField;
    
    private System.Xml.XmlQualifiedName resultIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Properties", Order=0)]
    public ItemProperty[] Properties
    {
        get
        {
            return this.propertiesField;
        }
        set
        {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ResultID
    {
        get
        {
            return this.resultIDField;
        }
        set
        {
            this.resultIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ItemProperty
{
    
    private object valueField;
    
    private string nameField;
    
    private string descriptionField;
    
    private string itemPathField;
    
    private string itemNameField;
    
    private System.Xml.XmlQualifiedName resultIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public object Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ResultID
    {
        get
        {
            return this.resultIDField;
        }
        set
        {
            this.resultIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ItemIdentifier
{
    
    private string itemPathField;
    
    private string itemNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class BrowseElement
{
    
    private ItemProperty[] propertiesField;
    
    private string nameField;
    
    private string itemPathField;
    
    private string itemNameField;
    
    private bool isItemField;
    
    private bool hasChildrenField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Properties", Order=0)]
    public ItemProperty[] Properties
    {
        get
        {
            return this.propertiesField;
        }
        set
        {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsItem
    {
        get
        {
            return this.isItemField;
        }
        set
        {
            this.isItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool HasChildren
    {
        get
        {
            return this.hasChildrenField;
        }
        set
        {
            this.hasChildrenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscribePolledRefreshReplyItemList
{
    
    private ItemValue[] itemsField;
    
    private string subscriptionHandleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Items", Order=0)]
    public ItemValue[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SubscriptionHandle
    {
        get
        {
            return this.subscriptionHandleField;
        }
        set
        {
            this.subscriptionHandleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ItemValue
{
    
    private string diagnosticInfoField;
    
    private object valueField;
    
    private OPCQuality qualityField;
    
    private System.Xml.XmlQualifiedName valueTypeQualifierField;
    
    private string itemPathField;
    
    private string itemNameField;
    
    private string clientItemHandleField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private System.Xml.XmlQualifiedName resultIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DiagnosticInfo
    {
        get
        {
            return this.diagnosticInfoField;
        }
        set
        {
            this.diagnosticInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public object Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public OPCQuality Quality
    {
        get
        {
            return this.qualityField;
        }
        set
        {
            this.qualityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ValueTypeQualifier
    {
        get
        {
            return this.valueTypeQualifierField;
        }
        set
        {
            this.valueTypeQualifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientItemHandle
    {
        get
        {
            return this.clientItemHandleField;
        }
        set
        {
            this.clientItemHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified
    {
        get
        {
            return this.timestampFieldSpecified;
        }
        set
        {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ResultID
    {
        get
        {
            return this.resultIDField;
        }
        set
        {
            this.resultIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class OPCQuality
{
    
    private qualityBits qualityFieldField;
    
    private limitBits limitFieldField;
    
    private byte vendorFieldField;
    
    public OPCQuality()
    {
        this.qualityFieldField = qualityBits.good;
        this.limitFieldField = limitBits.none;
        this.vendorFieldField = ((byte)(0));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(qualityBits.good)]
    public qualityBits QualityField
    {
        get
        {
            return this.qualityFieldField;
        }
        set
        {
            this.qualityFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(limitBits.none)]
    public limitBits LimitField
    {
        get
        {
            return this.limitFieldField;
        }
        set
        {
            this.limitFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte VendorField
    {
        get
        {
            return this.vendorFieldField;
        }
        set
        {
            this.vendorFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public enum qualityBits
{
    
    /// <remarks/>
    bad,
    
    /// <remarks/>
    badConfigurationError,
    
    /// <remarks/>
    badNotConnected,
    
    /// <remarks/>
    badDeviceFailure,
    
    /// <remarks/>
    badSensorFailure,
    
    /// <remarks/>
    badLastKnownValue,
    
    /// <remarks/>
    badCommFailure,
    
    /// <remarks/>
    badOutOfService,
    
    /// <remarks/>
    badWaitingForInitialData,
    
    /// <remarks/>
    uncertain,
    
    /// <remarks/>
    uncertainLastUsableValue,
    
    /// <remarks/>
    uncertainSensorNotAccurate,
    
    /// <remarks/>
    uncertainEUExceeded,
    
    /// <remarks/>
    uncertainSubNormal,
    
    /// <remarks/>
    good,
    
    /// <remarks/>
    goodLocalOverride,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public enum limitBits
{
    
    /// <remarks/>
    none,
    
    /// <remarks/>
    low,
    
    /// <remarks/>
    high,
    
    /// <remarks/>
    constant,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscribeItemValue
{
    
    private ItemValue itemValueField;
    
    private int revisedSamplingRateField;
    
    private bool revisedSamplingRateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ItemValue ItemValue
    {
        get
        {
            return this.itemValueField;
        }
        set
        {
            this.itemValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int RevisedSamplingRate
    {
        get
        {
            return this.revisedSamplingRateField;
        }
        set
        {
            this.revisedSamplingRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RevisedSamplingRateSpecified
    {
        get
        {
            return this.revisedSamplingRateFieldSpecified;
        }
        set
        {
            this.revisedSamplingRateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscribeReplyItemList
{
    
    private SubscribeItemValue[] itemsField;
    
    private int revisedSamplingRateField;
    
    private bool revisedSamplingRateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Items", Order=0)]
    public SubscribeItemValue[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int RevisedSamplingRate
    {
        get
        {
            return this.revisedSamplingRateField;
        }
        set
        {
            this.revisedSamplingRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RevisedSamplingRateSpecified
    {
        get
        {
            return this.revisedSamplingRateFieldSpecified;
        }
        set
        {
            this.revisedSamplingRateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscribeRequestItem
{
    
    private string itemPathField;
    
    private System.Xml.XmlQualifiedName reqTypeField;
    
    private string itemNameField;
    
    private string clientItemHandleField;
    
    private float deadbandField;
    
    private bool deadbandFieldSpecified;
    
    private int requestedSamplingRateField;
    
    private bool requestedSamplingRateFieldSpecified;
    
    private bool enableBufferingField;
    
    private bool enableBufferingFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ReqType
    {
        get
        {
            return this.reqTypeField;
        }
        set
        {
            this.reqTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientItemHandle
    {
        get
        {
            return this.clientItemHandleField;
        }
        set
        {
            this.clientItemHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Deadband
    {
        get
        {
            return this.deadbandField;
        }
        set
        {
            this.deadbandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeadbandSpecified
    {
        get
        {
            return this.deadbandFieldSpecified;
        }
        set
        {
            this.deadbandFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int RequestedSamplingRate
    {
        get
        {
            return this.requestedSamplingRateField;
        }
        set
        {
            this.requestedSamplingRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequestedSamplingRateSpecified
    {
        get
        {
            return this.requestedSamplingRateFieldSpecified;
        }
        set
        {
            this.requestedSamplingRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool EnableBuffering
    {
        get
        {
            return this.enableBufferingField;
        }
        set
        {
            this.enableBufferingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EnableBufferingSpecified
    {
        get
        {
            return this.enableBufferingFieldSpecified;
        }
        set
        {
            this.enableBufferingFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscribeRequestItemList
{
    
    private SubscribeRequestItem[] itemsField;
    
    private string itemPathField;
    
    private System.Xml.XmlQualifiedName reqTypeField;
    
    private float deadbandField;
    
    private bool deadbandFieldSpecified;
    
    private int requestedSamplingRateField;
    
    private bool requestedSamplingRateFieldSpecified;
    
    private bool enableBufferingField;
    
    private bool enableBufferingFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Items", Order=0)]
    public SubscribeRequestItem[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ReqType
    {
        get
        {
            return this.reqTypeField;
        }
        set
        {
            this.reqTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Deadband
    {
        get
        {
            return this.deadbandField;
        }
        set
        {
            this.deadbandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeadbandSpecified
    {
        get
        {
            return this.deadbandFieldSpecified;
        }
        set
        {
            this.deadbandFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int RequestedSamplingRate
    {
        get
        {
            return this.requestedSamplingRateField;
        }
        set
        {
            this.requestedSamplingRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequestedSamplingRateSpecified
    {
        get
        {
            return this.requestedSamplingRateFieldSpecified;
        }
        set
        {
            this.requestedSamplingRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool EnableBuffering
    {
        get
        {
            return this.enableBufferingField;
        }
        set
        {
            this.enableBufferingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EnableBufferingSpecified
    {
        get
        {
            return this.enableBufferingFieldSpecified;
        }
        set
        {
            this.enableBufferingFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class WriteRequestItemList
{
    
    private ItemValue[] itemsField;
    
    private string itemPathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Items", Order=0)]
    public ItemValue[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class OPCError
{
    
    private string textField;
    
    private System.Xml.XmlQualifiedName idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ReplyItemList
{
    
    private ItemValue[] itemsField;
    
    private string reservedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Items", Order=0)]
    public ItemValue[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Reserved
    {
        get
        {
            return this.reservedField;
        }
        set
        {
            this.reservedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ReadRequestItem
{
    
    private string itemPathField;
    
    private System.Xml.XmlQualifiedName reqTypeField;
    
    private string itemNameField;
    
    private string clientItemHandleField;
    
    private int maxAgeField;
    
    private bool maxAgeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ReqType
    {
        get
        {
            return this.reqTypeField;
        }
        set
        {
            this.reqTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientItemHandle
    {
        get
        {
            return this.clientItemHandleField;
        }
        set
        {
            this.clientItemHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int MaxAge
    {
        get
        {
            return this.maxAgeField;
        }
        set
        {
            this.maxAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxAgeSpecified
    {
        get
        {
            return this.maxAgeFieldSpecified;
        }
        set
        {
            this.maxAgeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ReadRequestItemList
{
    
    private ReadRequestItem[] itemsField;
    
    private string itemPathField;
    
    private System.Xml.XmlQualifiedName reqTypeField;
    
    private int maxAgeField;
    
    private bool maxAgeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Items", Order=0)]
    public ReadRequestItem[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Xml.XmlQualifiedName ReqType
    {
        get
        {
            return this.reqTypeField;
        }
        set
        {
            this.reqTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int MaxAge
    {
        get
        {
            return this.maxAgeField;
        }
        set
        {
            this.maxAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxAgeSpecified
    {
        get
        {
            return this.maxAgeFieldSpecified;
        }
        set
        {
            this.maxAgeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class RequestOptions
{
    
    private bool returnErrorTextField;
    
    private bool returnDiagnosticInfoField;
    
    private bool returnItemTimeField;
    
    private bool returnItemPathField;
    
    private bool returnItemNameField;
    
    private System.DateTime requestDeadlineField;
    
    private bool requestDeadlineFieldSpecified;
    
    private string clientRequestHandleField;
    
    private string localeIDField;
    
    public RequestOptions()
    {
        this.returnErrorTextField = true;
        this.returnDiagnosticInfoField = false;
        this.returnItemTimeField = false;
        this.returnItemPathField = false;
        this.returnItemNameField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool ReturnErrorText
    {
        get
        {
            return this.returnErrorTextField;
        }
        set
        {
            this.returnErrorTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnDiagnosticInfo
    {
        get
        {
            return this.returnDiagnosticInfoField;
        }
        set
        {
            this.returnDiagnosticInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnItemTime
    {
        get
        {
            return this.returnItemTimeField;
        }
        set
        {
            this.returnItemTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnItemPath
    {
        get
        {
            return this.returnItemPathField;
        }
        set
        {
            this.returnItemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnItemName
    {
        get
        {
            return this.returnItemNameField;
        }
        set
        {
            this.returnItemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime RequestDeadline
    {
        get
        {
            return this.requestDeadlineField;
        }
        set
        {
            this.requestDeadlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequestDeadlineSpecified
    {
        get
        {
            return this.requestDeadlineFieldSpecified;
        }
        set
        {
            this.requestDeadlineFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocaleID
    {
        get
        {
            return this.localeIDField;
        }
        set
        {
            this.localeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ServerStatus
{
    
    private string statusInfoField;
    
    private string vendorInfoField;
    
    private string[] supportedLocaleIDsField;
    
    private interfaceVersion[] supportedInterfaceVersionsField;
    
    private System.DateTime startTimeField;
    
    private string productVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string StatusInfo
    {
        get
        {
            return this.statusInfoField;
        }
        set
        {
            this.statusInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string VendorInfo
    {
        get
        {
            return this.vendorInfoField;
        }
        set
        {
            this.vendorInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupportedLocaleIDs", Order=2)]
    public string[] SupportedLocaleIDs
    {
        get
        {
            return this.supportedLocaleIDsField;
        }
        set
        {
            this.supportedLocaleIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupportedInterfaceVersions", Order=3)]
    public interfaceVersion[] SupportedInterfaceVersions
    {
        get
        {
            return this.supportedInterfaceVersionsField;
        }
        set
        {
            this.supportedInterfaceVersionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductVersion
    {
        get
        {
            return this.productVersionField;
        }
        set
        {
            this.productVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public enum interfaceVersion
{
    
    /// <remarks/>
    XML_DA_Version_1_0,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ReplyBase
{
    
    private System.DateTime rcvTimeField;
    
    private System.DateTime replyTimeField;
    
    private string clientRequestHandleField;
    
    private string revisedLocaleIDField;
    
    private serverState serverStateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime RcvTime
    {
        get
        {
            return this.rcvTimeField;
        }
        set
        {
            this.rcvTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ReplyTime
    {
        get
        {
            return this.replyTimeField;
        }
        set
        {
            this.replyTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RevisedLocaleID
    {
        get
        {
            return this.revisedLocaleIDField;
        }
        set
        {
            this.revisedLocaleIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public serverState ServerState
    {
        get
        {
            return this.serverStateField;
        }
        set
        {
            this.serverStateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public enum serverState
{
    
    /// <remarks/>
    running,
    
    /// <remarks/>
    failed,
    
    /// <remarks/>
    noConfig,
    
    /// <remarks/>
    suspended,
    
    /// <remarks/>
    test,
    
    /// <remarks/>
    commFault,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class GetStatusResponse
{
    
    private ReplyBase getStatusResultField;
    
    private ServerStatus statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase GetStatusResult
    {
        get
        {
            return this.getStatusResultField;
        }
        set
        {
            this.getStatusResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ServerStatus Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public GetStatus GetStatus;
    
    public GetStatusRequest()
    {
    }
    
    public GetStatusRequest(GetStatus GetStatus)
    {
        this.GetStatus = GetStatus;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetStatusResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public GetStatusResponse GetStatusResponse;
    
    public GetStatusResponse1()
    {
    }
    
    public GetStatusResponse1(GetStatusResponse GetStatusResponse)
    {
        this.GetStatusResponse = GetStatusResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class Read
{
    
    private RequestOptions optionsField;
    
    private ReadRequestItemList itemListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RequestOptions Options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ReadRequestItemList ItemList
    {
        get
        {
            return this.itemListField;
        }
        set
        {
            this.itemListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class ReadResponse
{
    
    private ReplyBase readResultField;
    
    private ReplyItemList rItemListField;
    
    private OPCError[] errorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase ReadResult
    {
        get
        {
            return this.readResultField;
        }
        set
        {
            this.readResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ReplyItemList RItemList
    {
        get
        {
            return this.rItemListField;
        }
        set
        {
            this.rItemListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=2)]
    public OPCError[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public Read Read;
    
    public ReadRequest()
    {
    }
    
    public ReadRequest(Read Read)
    {
        this.Read = Read;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ReadResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public ReadResponse ReadResponse;
    
    public ReadResponse1()
    {
    }
    
    public ReadResponse1(ReadResponse ReadResponse)
    {
        this.ReadResponse = ReadResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class Write
{
    
    private RequestOptions optionsField;
    
    private WriteRequestItemList itemListField;
    
    private bool returnValuesOnReplyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RequestOptions Options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public WriteRequestItemList ItemList
    {
        get
        {
            return this.itemListField;
        }
        set
        {
            this.itemListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReturnValuesOnReply
    {
        get
        {
            return this.returnValuesOnReplyField;
        }
        set
        {
            this.returnValuesOnReplyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class WriteResponse
{
    
    private ReplyBase writeResultField;
    
    private ReplyItemList rItemListField;
    
    private OPCError[] errorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase WriteResult
    {
        get
        {
            return this.writeResultField;
        }
        set
        {
            this.writeResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ReplyItemList RItemList
    {
        get
        {
            return this.rItemListField;
        }
        set
        {
            this.rItemListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=2)]
    public OPCError[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class WriteRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public Write Write;
    
    public WriteRequest()
    {
    }
    
    public WriteRequest(Write Write)
    {
        this.Write = Write;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class WriteResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public WriteResponse WriteResponse;
    
    public WriteResponse1()
    {
    }
    
    public WriteResponse1(WriteResponse WriteResponse)
    {
        this.WriteResponse = WriteResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class Subscribe
{
    
    private RequestOptions optionsField;
    
    private SubscribeRequestItemList itemListField;
    
    private bool returnValuesOnReplyField;
    
    private int subscriptionPingRateField;
    
    public Subscribe()
    {
        this.subscriptionPingRateField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RequestOptions Options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SubscribeRequestItemList ItemList
    {
        get
        {
            return this.itemListField;
        }
        set
        {
            this.itemListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReturnValuesOnReply
    {
        get
        {
            return this.returnValuesOnReplyField;
        }
        set
        {
            this.returnValuesOnReplyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int SubscriptionPingRate
    {
        get
        {
            return this.subscriptionPingRateField;
        }
        set
        {
            this.subscriptionPingRateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscribeResponse
{
    
    private ReplyBase subscribeResultField;
    
    private SubscribeReplyItemList rItemListField;
    
    private OPCError[] errorsField;
    
    private string serverSubHandleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase SubscribeResult
    {
        get
        {
            return this.subscribeResultField;
        }
        set
        {
            this.subscribeResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SubscribeReplyItemList RItemList
    {
        get
        {
            return this.rItemListField;
        }
        set
        {
            this.rItemListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=2)]
    public OPCError[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServerSubHandle
    {
        get
        {
            return this.serverSubHandleField;
        }
        set
        {
            this.serverSubHandleField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubscribeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public Subscribe Subscribe;
    
    public SubscribeRequest()
    {
    }
    
    public SubscribeRequest(Subscribe Subscribe)
    {
        this.Subscribe = Subscribe;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubscribeResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public SubscribeResponse SubscribeResponse;
    
    public SubscribeResponse1()
    {
    }
    
    public SubscribeResponse1(SubscribeResponse SubscribeResponse)
    {
        this.SubscribeResponse = SubscribeResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscriptionPolledRefresh
{
    
    private RequestOptions optionsField;
    
    private string[] serverSubHandlesField;
    
    private System.DateTime holdTimeField;
    
    private bool holdTimeFieldSpecified;
    
    private int waitTimeField;
    
    private bool returnAllItemsField;
    
    public SubscriptionPolledRefresh()
    {
        this.waitTimeField = 0;
        this.returnAllItemsField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public RequestOptions Options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServerSubHandles", Order=1)]
    public string[] ServerSubHandles
    {
        get
        {
            return this.serverSubHandlesField;
        }
        set
        {
            this.serverSubHandlesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime HoldTime
    {
        get
        {
            return this.holdTimeField;
        }
        set
        {
            this.holdTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HoldTimeSpecified
    {
        get
        {
            return this.holdTimeFieldSpecified;
        }
        set
        {
            this.holdTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int WaitTime
    {
        get
        {
            return this.waitTimeField;
        }
        set
        {
            this.waitTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnAllItems
    {
        get
        {
            return this.returnAllItemsField;
        }
        set
        {
            this.returnAllItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscriptionPolledRefreshResponse
{
    
    private ReplyBase subscriptionPolledRefreshResultField;
    
    private string[] invalidServerSubHandlesField;
    
    private SubscribePolledRefreshReplyItemList[] rItemListField;
    
    private OPCError[] errorsField;
    
    private bool dataBufferOverflowField;
    
    public SubscriptionPolledRefreshResponse()
    {
        this.dataBufferOverflowField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase SubscriptionPolledRefreshResult
    {
        get
        {
            return this.subscriptionPolledRefreshResultField;
        }
        set
        {
            this.subscriptionPolledRefreshResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InvalidServerSubHandles", Order=1)]
    public string[] InvalidServerSubHandles
    {
        get
        {
            return this.invalidServerSubHandlesField;
        }
        set
        {
            this.invalidServerSubHandlesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RItemList", Order=2)]
    public SubscribePolledRefreshReplyItemList[] RItemList
    {
        get
        {
            return this.rItemListField;
        }
        set
        {
            this.rItemListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=3)]
    public OPCError[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DataBufferOverflow
    {
        get
        {
            return this.dataBufferOverflowField;
        }
        set
        {
            this.dataBufferOverflowField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubscriptionPolledRefreshRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public SubscriptionPolledRefresh SubscriptionPolledRefresh;
    
    public SubscriptionPolledRefreshRequest()
    {
    }
    
    public SubscriptionPolledRefreshRequest(SubscriptionPolledRefresh SubscriptionPolledRefresh)
    {
        this.SubscriptionPolledRefresh = SubscriptionPolledRefresh;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubscriptionPolledRefreshResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public SubscriptionPolledRefreshResponse SubscriptionPolledRefreshResponse;
    
    public SubscriptionPolledRefreshResponse1()
    {
    }
    
    public SubscriptionPolledRefreshResponse1(SubscriptionPolledRefreshResponse SubscriptionPolledRefreshResponse)
    {
        this.SubscriptionPolledRefreshResponse = SubscriptionPolledRefreshResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscriptionCancel
{
    
    private string serverSubHandleField;
    
    private string clientRequestHandleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServerSubHandle
    {
        get
        {
            return this.serverSubHandleField;
        }
        set
        {
            this.serverSubHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class SubscriptionCancelResponse
{
    
    private string clientRequestHandleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubscriptionCancelRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public SubscriptionCancel SubscriptionCancel;
    
    public SubscriptionCancelRequest()
    {
    }
    
    public SubscriptionCancelRequest(SubscriptionCancel SubscriptionCancel)
    {
        this.SubscriptionCancel = SubscriptionCancel;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SubscriptionCancelResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public SubscriptionCancelResponse SubscriptionCancelResponse;
    
    public SubscriptionCancelResponse1()
    {
    }
    
    public SubscriptionCancelResponse1(SubscriptionCancelResponse SubscriptionCancelResponse)
    {
        this.SubscriptionCancelResponse = SubscriptionCancelResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class Browse
{
    
    private System.Xml.XmlQualifiedName[] propertyNamesField;
    
    private string localeIDField;
    
    private string clientRequestHandleField;
    
    private string itemPathField;
    
    private string itemNameField;
    
    private string continuationPointField;
    
    private int maxElementsReturnedField;
    
    private browseFilter browseFilterField;
    
    private string elementNameFilterField;
    
    private string vendorFilterField;
    
    private bool returnAllPropertiesField;
    
    private bool returnPropertyValuesField;
    
    private bool returnErrorTextField;
    
    public Browse()
    {
        this.maxElementsReturnedField = 0;
        this.browseFilterField = browseFilter.all;
        this.returnAllPropertiesField = false;
        this.returnPropertyValuesField = false;
        this.returnErrorTextField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyNames", Order=0)]
    public System.Xml.XmlQualifiedName[] PropertyNames
    {
        get
        {
            return this.propertyNamesField;
        }
        set
        {
            this.propertyNamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocaleID
    {
        get
        {
            return this.localeIDField;
        }
        set
        {
            this.localeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemName
    {
        get
        {
            return this.itemNameField;
        }
        set
        {
            this.itemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ContinuationPoint
    {
        get
        {
            return this.continuationPointField;
        }
        set
        {
            this.continuationPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int MaxElementsReturned
    {
        get
        {
            return this.maxElementsReturnedField;
        }
        set
        {
            this.maxElementsReturnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(browseFilter.all)]
    public browseFilter BrowseFilter
    {
        get
        {
            return this.browseFilterField;
        }
        set
        {
            this.browseFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ElementNameFilter
    {
        get
        {
            return this.elementNameFilterField;
        }
        set
        {
            this.elementNameFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VendorFilter
    {
        get
        {
            return this.vendorFilterField;
        }
        set
        {
            this.vendorFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnAllProperties
    {
        get
        {
            return this.returnAllPropertiesField;
        }
        set
        {
            this.returnAllPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnPropertyValues
    {
        get
        {
            return this.returnPropertyValuesField;
        }
        set
        {
            this.returnPropertyValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnErrorText
    {
        get
        {
            return this.returnErrorTextField;
        }
        set
        {
            this.returnErrorTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public enum browseFilter
{
    
    /// <remarks/>
    all,
    
    /// <remarks/>
    branch,
    
    /// <remarks/>
    item,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class BrowseResponse
{
    
    private ReplyBase browseResultField;
    
    private BrowseElement[] elementsField;
    
    private OPCError[] errorsField;
    
    private string continuationPointField;
    
    private bool moreElementsField;
    
    public BrowseResponse()
    {
        this.moreElementsField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase BrowseResult
    {
        get
        {
            return this.browseResultField;
        }
        set
        {
            this.browseResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Elements", Order=1)]
    public BrowseElement[] Elements
    {
        get
        {
            return this.elementsField;
        }
        set
        {
            this.elementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=2)]
    public OPCError[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ContinuationPoint
    {
        get
        {
            return this.continuationPointField;
        }
        set
        {
            this.continuationPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool MoreElements
    {
        get
        {
            return this.moreElementsField;
        }
        set
        {
            this.moreElementsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class BrowseRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public Browse Browse;
    
    public BrowseRequest()
    {
    }
    
    public BrowseRequest(Browse Browse)
    {
        this.Browse = Browse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class BrowseResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public BrowseResponse BrowseResponse;
    
    public BrowseResponse1()
    {
    }
    
    public BrowseResponse1(BrowseResponse BrowseResponse)
    {
        this.BrowseResponse = BrowseResponse;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class GetProperties
{
    
    private ItemIdentifier[] itemIDsField;
    
    private System.Xml.XmlQualifiedName[] propertyNamesField;
    
    private string localeIDField;
    
    private string clientRequestHandleField;
    
    private string itemPathField;
    
    private bool returnAllPropertiesField;
    
    private bool returnPropertyValuesField;
    
    private bool returnErrorTextField;
    
    public GetProperties()
    {
        this.returnAllPropertiesField = false;
        this.returnPropertyValuesField = false;
        this.returnErrorTextField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemIDs", Order=0)]
    public ItemIdentifier[] ItemIDs
    {
        get
        {
            return this.itemIDsField;
        }
        set
        {
            this.itemIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyNames", Order=1)]
    public System.Xml.XmlQualifiedName[] PropertyNames
    {
        get
        {
            return this.propertyNamesField;
        }
        set
        {
            this.propertyNamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocaleID
    {
        get
        {
            return this.localeIDField;
        }
        set
        {
            this.localeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientRequestHandle
    {
        get
        {
            return this.clientRequestHandleField;
        }
        set
        {
            this.clientRequestHandleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemPath
    {
        get
        {
            return this.itemPathField;
        }
        set
        {
            this.itemPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnAllProperties
    {
        get
        {
            return this.returnAllPropertiesField;
        }
        set
        {
            this.returnAllPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnPropertyValues
    {
        get
        {
            return this.returnPropertyValuesField;
        }
        set
        {
            this.returnPropertyValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReturnErrorText
    {
        get
        {
            return this.returnErrorTextField;
        }
        set
        {
            this.returnErrorTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/")]
public partial class GetPropertiesResponse
{
    
    private ReplyBase getPropertiesResultField;
    
    private PropertyReplyList[] propertyListsField;
    
    private OPCError[] errorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyBase GetPropertiesResult
    {
        get
        {
            return this.getPropertiesResultField;
        }
        set
        {
            this.getPropertiesResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyLists", Order=1)]
    public PropertyReplyList[] PropertyLists
    {
        get
        {
            return this.propertyListsField;
        }
        set
        {
            this.propertyListsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=2)]
    public OPCError[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPropertiesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public GetProperties GetProperties;
    
    public GetPropertiesRequest()
    {
    }
    
    public GetPropertiesRequest(GetProperties GetProperties)
    {
        this.GetProperties = GetProperties;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPropertiesResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://opcfoundation.org/webservices/XMLDA/1.0/", Order=0)]
    public GetPropertiesResponse GetPropertiesResponse;
    
    public GetPropertiesResponse1()
    {
    }
    
    public GetPropertiesResponse1(GetPropertiesResponse GetPropertiesResponse)
    {
        this.GetPropertiesResponse = GetPropertiesResponse;
    }
}
